baseURL = "https://liaobinbin.com/"
languageCode = "zh-cn"
title = "Boiao Ch"
theme = "hemingway"
copyright = "&copy; <a href=\"https://liaobinbin.com\"> Boiao Ch</a> 2008 - 2018"
#disqusShortname = "bobslogs"
publishdir = "docs"

[parames]

[params.comment]
type = "valine"

[params.comment.valine]
id = "E0lUSj6zDajetA3pKlP4h90b-MdYXbMMI"
key = "k6dTtx4wkg0MfOodf4mO0Wy5"
placeholder = "Write something ..."
avatar = "retro"

[params.highlight]
style = "base16/solarized-light"
languages = ["bash", "typescript", "javascript", "go", "dockerfile", "json", "c", "cpp", "css"]

[[params.social]]
url = "https://github.com/liaobinbin"
fa_icon = "fa-github"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss" 

[markup.goldmark.renderer]
unsafe = true
