baseURL = "https://liaobinbin.com/"
languageCode = "zh-cn"
title = "Boiao Ch"
theme = "LoveIt"
copyright = "&copy; <a href=\"https://liaobinbin.com\"> Boiao Ch</a> 2008 - 2018"
publishdir = "docs"
hasCJKLanguage = true
enableEmoji = true


defaultContentLanguage = "zh-cn"

[author]
  name = "Boiao Ch"
  email = "doubiliao@gmail.com"
  link = "https://liaobinbin.com"

[menu]
  [[menu.main]]
   weight = 1
   identifier = "posts"
   pre = ""
   post = ""
   name = "文章"
   url = "/posts/"
   title = ""
  [[menu.main]]
   weight = 2
   identifier = "categories"
   pre = ""
   post = ""
   name = "分类"
   url = "/categories/"
   title = ""
  [[menu.main]]
   weight = 3
   identifier = ""
   pre = ""
   post = ""
   name = "关于"
   url = "/about/"
   title = ""

[markup]
  [markup.highlight]
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.comment]
  type = "valine"

[params.comment.valine]
  id = "XIo8KShyg27BUQNLIDGqtjhj-gzGzoHsz"
  key = "6AGQbwYr9G7NhVKfqxiOnV4y"
  placeholder = "Write something ..."
  avatar = "retro"

[params.highlight]
  style = "base16/solarized-light"
  languages = ["bash", "typescript", "javascript", "go", "dockerfile", "json", "c", "cpp", "css", "lisp"]

#[markup.goldmark.renderer]
# unsafe = true
